2022-03-23T14:35:31,696 Using pip 21.3.1 from /home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip (python 3.9)
2022-03-23T14:35:31,698 Non-user install because site-packages writeable
2022-03-23T14:35:31,768 Created temporary directory: /tmp/pip-ephem-wheel-cache-bmnz54kh
2022-03-23T14:35:31,768 Created temporary directory: /tmp/pip-req-tracker-lmaxcdm5
2022-03-23T14:35:31,768 Initialized build tracking at /tmp/pip-req-tracker-lmaxcdm5
2022-03-23T14:35:31,768 Created build tracker: /tmp/pip-req-tracker-lmaxcdm5
2022-03-23T14:35:31,768 Entered build tracker: /tmp/pip-req-tracker-lmaxcdm5
2022-03-23T14:35:31,768 Created temporary directory: /tmp/pip-install-9bzzhb3s
2022-03-23T14:35:31,781 Processing /home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion
2022-03-23T14:35:31,782   Added file:///home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion to build tracker '/tmp/pip-req-tracker-lmaxcdm5'
2022-03-23T14:35:31,782   Running setup.py (path:/home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/setup.py) egg_info for package from file:///home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion
2022-03-23T14:35:31,782   Created temporary directory: /tmp/pip-pip-egg-info-uofipszc
2022-03-23T14:35:31,782   Running command python setup.py egg_info
2022-03-23T14:35:32,218   /home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/pyequion/activity/coo_tensor_ops/coo_tensor_ops.pyx
2022-03-23T14:35:32,218     tree = Parsing.p_module(s, pxd, full_module_name)

2022-03-23T14:35:32,487   Error compiling Cython file:
2022-03-23T14:35:32,487   ------------------------------------------------------------
2022-03-23T14:35:32,487   ...
2022-03-23T14:35:32,487   import numpy as np


2022-03-23T14:35:32,487   @cython.boundscheck(False)  # Deactivate bounds checking
2022-03-23T14:35:32,487   ^
2022-03-23T14:35:32,487   ------------------------------------------------------------

2022-03-23T14:35:32,487   pyequion/activity/coo_tensor_ops/coo_tensor_ops.pyx:4:0: undeclared name not builtin: cython
2022-03-23T14:35:32,749   Traceback (most recent call last):
2022-03-23T14:35:32,749     File "<string>", line 1, in <module>
2022-03-23T14:35:32,749     File "/home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/setup.py", line 33, in <module>
2022-03-23T14:35:32,749       ext_modules=cythonize([ext]),
2022-03-23T14:35:32,749     File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1103, in cythonize
2022-03-23T14:35:32,750       cythonize_one(*args)
2022-03-23T14:35:32,750     File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1226, in cythonize_one
2022-03-23T14:35:32,750       raise CompileError(None, pyx_file)
2022-03-23T14:35:32,750   Cython.Compiler.Errors.CompileError: /home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/pyequion/activity/coo_tensor_ops/coo_tensor_ops.pyx
2022-03-23T14:35:32,750   Compiling /home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/pyequion/activity/coo_tensor_ops/coo_tensor_ops.pyx because it changed.
2022-03-23T14:35:32,750   [1/1] Cythonizing /home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion/pyequion/activity/coo_tensor_ops/coo_tensor_ops.pyx
2022-03-23T14:35:32,879 WARNING: Discarding file:///home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2022-03-23T14:35:32,879 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2022-03-23T14:35:32,880 Exception information:
2022-03-23T14:35:32,880 Traceback (most recent call last):
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
2022-03-23T14:35:32,880     status = run_func(*args)
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
2022-03-23T14:35:32,880     return func(self, options, args)
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 338, in run
2022-03-23T14:35:32,880     requirement_set = resolver.resolve(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
2022-03-23T14:35:32,880     collected = self.factory.collect_root_requirements(root_reqs)
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in collect_root_requirements
2022-03-23T14:35:32,880     req = self._make_requirement_from_install_req(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 445, in _make_requirement_from_install_req
2022-03-23T14:35:32,880     raise self._build_failures[ireq.link]
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 201, in _make_candidate_from_link
2022-03-23T14:35:32,880     self._link_candidate_cache[link] = LinkCandidate(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 281, in __init__
2022-03-23T14:35:32,880     super().__init__(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2022-03-23T14:35:32,880     self.dist = self._prepare()
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
2022-03-23T14:35:32,880     dist = self._prepare_distribution()
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
2022-03-23T14:35:32,880     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
2022-03-23T14:35:32,880     return self._prepare_linked_requirement(req, parallel_builds)
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
2022-03-23T14:35:32,880     dist = _get_prepared_distribution(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
2022-03-23T14:35:32,880     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
2022-03-23T14:35:32,880     self.req.prepare_metadata()
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 561, in prepare_metadata
2022-03-23T14:35:32,880     self.metadata_directory = generate_metadata_legacy(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 59, in generate_metadata
2022-03-23T14:35:32,880     call_subprocess(
2022-03-23T14:35:32,880   File "/home/dfnaiff/miniconda3/envs/mainenv/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 254, in call_subprocess
2022-03-23T14:35:32,880     raise InstallationSubprocessError(proc.returncode, command_desc)
2022-03-23T14:35:32,880 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2022-03-23T14:35:32,886 Removed file:///home/dfnaiff/Danilo/NIDF/Projects/PyEquion2/pyequion from build tracker '/tmp/pip-req-tracker-lmaxcdm5'
2022-03-23T14:35:32,886 Removed build tracker: '/tmp/pip-req-tracker-lmaxcdm5'
